# Generated by Django 3.0.5 on 2020-04-27 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Blog Title')),
                ('slug', models.SlugField(blank=True, default=None, null=True, verbose_name='Blog slug')),
                ('description', models.TextField(max_length=10000, null=True, verbose_name='Domain description')),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
