# Generated by Django 3.0.5 on 2020-04-28 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_venue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Venue',
        ),
    ]
